import { expect, test } from "vitest";
import { ManhattanDistance, expandUniverse, partOne, partTwo } from "./day11";
import { readInput } from "../utils";

const originalInput = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`;

const myInput = readInput("ts/day11/input.txt");

test("Part One - Cosmic Expansion", () => {
  // expect(partOne(originalInput, 2)).toBe(374);
  // expect(partOne(myInput)).toBe(9627977);
});

// test("expandUniverse()", () => {
//   expect(expandUniverse(originalInput)).toStrictEqual(`....#........
// .........#...
// #............
// .............
// .............
// ........#....
// .#...........
// ............#
// .............
// .............
// .........#...
// #....#.......`);
// });

// test("ManhattanDistance()", () => {
//   expect(ManhattanDistance({ x: 0, y: 4 }, { x: 10, y: 9 })).toBe(15);
//   expect(ManhattanDistance({ x: 2, y: 0 }, { x: 7, y: 12 })).toBe(17);
//   expect(ManhattanDistance({ x: 11, y: 0 }, { x: 11, y: 5 })).toBe(5);
// });

test("Part Two - Cosmic Expansion", () => {
  // expect(partTwo(originalInput)).toBe(1030);
  // expect(partOne(originalInput, 10)).toBe(1030);
  // expect(partOne(originalInput, 100)).toBe(8410);
  expect(partTwo(myInput)).toBe(9627977);
});
